Globs:
  LinuxChromeProfiles:
    - /home/*/.config/google-chrome
    - /home/*/.config/chrome-remote-desktop/chrome-profile
    - /home/*/.config/chromium
    - /home/*/{snap/brave/*/,}.config/BraveSoftware/Brave-Browser
  WindowsChromeProfiles:
    - C:\Users\*\AppData\{Roaming,Local}/BraveSoftware/Brave*/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/BraveSoftware/Brave*/User Data
    - C:\Users\*\AppData\{Roaming,Local}/Google/Chrome*/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/Google/Chrome*/User Data
    - C:\Users\*\AppData\{Roaming,Local}/Chromium*/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/Chromium*/User Data
    - C:\Users\*\AppData\{Roaming,Local}/Microsoft/Edge*/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/Microsoft/Edge*/User Data
    - C:\Users\*\AppData\{Roaming,Local}\Opera Software\Opera Stable\
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\Opera Software\Opera Stable\
    - C:\Users\*\AppData\{Roaming,Local}/Island/Island/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/Island/Island/User Data
    - C:\Users\*\AppData\{Roaming,Local}/Palo Alto Networks/PrismaAccessBrowser/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/Palo Alto Networks/PrismaAccessBrowser/User Data
    - C:\Users\*\AppData\{Roaming,Local}/Comodo/{Chromodo,Dragon}/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/Comodo/{Chromodo,Dragon}/User Data
    - C:\Users\*\AppData\{Roaming,Local}/Vivaldi/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/Vivaldi/User Data
    - C:\Users\*\AppData\Local\Packages\TheBrowserCompany.Arc_*\LocalCache\Local\Arc\User Data
    - C:\Users\*\AppData\{Roaming,Local}/EPISoftware/EpiBrowser/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/EPISoftware/EpiBrowser/User Data
    - C:\Users\*\AppData\{Roaming,Local}/AVAST Software/Browser/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/AVAST Software/Browser/User Data
    - C:\Users\*\AppData\{Roaming,Local}/CentBrowser/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/CentBrowser/User Data
    - C:\Users\*\AppData\{Roaming,Local}/CryptoTab Browser/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/CryptoTab Browser/User Data
    - C:\Users\*\AppData\{Roaming,Local}/Shift/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/Shift/User Data
    - C:\Users\*\AppData\{Roaming,Local}/Slimjet/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/Slimjet/User Data
    - C:\Users\*\AppData\{Roaming,Local}/WaveBrowser/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/WaveBrowser/User Data
    - C:\Users\*\AppData\{Roaming,Local}/Yandex/YandexBrowser/User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}/Yandex/YandexBrowser/User Data
  MacOSChromeProfiles:
    - /Users/*/Library/Application Support/BraveSoftware/Brave*/
    - /Users/*/Library/Application Support/Google/Chrome*/
    - /Users/*/Library/Application Support/Microsoft Edge*/
    - /Users/*/Library/Application Support/Chromium*/
    - /Users/*/Library/Application Support/PAB/Prisma Access Browser/
  WindowsFirefoxProfiles:
    - C:\Users\*\AppData\{Roaming,Local}\Mozilla\Firefox\Profiles
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\Mozilla\Firefox\Profiles
    - C:\Users\*\AppData\{Roaming,Local}\librewolf\Profiles
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\librewolf\Profiles
    - C:\Users\*\AppData\{Roaming,Local}\Waterfox\Profiles
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\Waterfox\Profiles
    - C:\Users\*\AppData\{Roaming,Local}\zen\Profiles
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\zen\Profiles
    - C:\Users\*\Desktop\Tor Browser\Browser\TorBrowser\Data\Browser
    - C:\Users\*\AppData\{Roaming,Local}\Mullvad\MullvadBrowser\Profiles
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\Mullvad\MullvadBrowser\Profiles
    - C:\Users\*\AppData\{Roaming,Local}\Floorp\Profiles
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\Floorp\Profiles
    - C:\Users\*\AppData\{Roaming,Local}\Moonchild Productions\Pale Moon\Profiles
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\Moonchild Productions\Pale Moon\Profiles
    - C:\Users\*\AppData\{Roaming,Local}\Moonchild Productions\Basilisk\Profiles
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\Moonchild Productions\Basilisk\Profiles
    - C:\Users\*\AppData\{Roaming,Local}\Basilisk-Dev\Basilisk\Profiles
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\Basilisk-Dev\Basilisk\Profiles
    - C:\Users\*\AppData\{Roaming,Local}\Mozilla\SeaMonkey\Profiles
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\Mozilla\SeaMonkey\Profiles
    - C:\Users\*\AppData\{Roaming,Local}\K-Meleon
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\K-Meleon
    - C:\Users\*\AppData\{Roaming,Local}\Comodo\IceDragon\Profiles
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\Comodo\IceDragon\Profiles
  LinuxFirefoxProfiles:
    - /home/*/.mozilla/firefox/*.default*
    - /home/*/snap/firefox/common/.mozilla/firefox/*.default*
  MacOSFirefoxProfiles:
    - /Users/*/Library/Application Support/Firefox/Profiles
    - /Users/*/Library/Application Support/librewolf/Profiles
    - /Users/*/Library/Application Support/Waterfox/Profiles
    - /Users/*/Library/Application Support/zen/Profiles
    - /Users/*/Library/Application Support/TorBrowser-Data/Browser
    - /Users/*/Library/Application Support/MullvadBrowser/Profiles
    - /Users/*/Library/Application Support/Floorp/Profiles
    - /Users/*/Library/Application Support/Pale Moon/Profiles
    - /Users/*/Library/Application Support/Basilisk/Profiles
    - /Users/*/Library/Application Support/SeaMonkey/Profiles
