Globs:
  LinuxChromeProfiles:
    - /home/*/.config/google-chrome
    - /home/*/.config/chrome-remote-desktop/chrome-profile
    - /home/*/.config/chromium
    - /home/*/{snap/brave/*/,}.config/BraveSoftware/Brave-Browser
  WindowsChromeProfiles:
    - C:\Users\*\AppData\{Roaming,Local}\*\*\User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\*\*\User Data
    - C:\Users\*\AppData\{Roaming,Local}\*\User Data
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\*\User Data
    - C:\Users\*\AppData\{Roaming,Local}\Opera Software\Opera*\
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\Opera Software\Opera*\
    - C:\Users\*\AppData\Local\Packages\TheBrowserCompany.Arc_*\LocalCache\Local\Arc\User Data
  MacOSChromeProfiles:
    - /Users/*/Library/Application Support/*/*/
    - /Users/*/Library/Application Support/*/
  WindowsFirefoxProfiles:
    - C:\Users\*\AppData\{Roaming,Local}\*\*\Profiles
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\*\*\Profiles
    - C:\Users\*\AppData\{Roaming,Local}\*\Profiles
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\*\Profiles
    - C:\Users\*\Desktop\Tor Browser\Browser\TorBrowser\Data\Browser
    - C:\Users\*\AppData\{Roaming,Local}\K-Meleon
    - C:\Windows\{System32,SysWOW64}\config\systemprofile\AppData\{Roaming,Local}\K-Meleon
  LinuxFirefoxProfiles:
    - /home/*/.mozilla/firefox/*.default*
    - /home/*/snap/firefox/common/.mozilla/firefox/*.default*
  MacOSFirefoxProfiles:
    - /Users/*/Library/Application Support/*/Profiles
    - /Users/*/Library/Application Support/TorBrowser-Data/Browser
